ex-gwe-ates = [
    "mf6/example/ex-gwe-ates",
]
ex-gwe-barends = [
    "mf6/example/ex-gwe-barends/mf6gwf",
    "mf6/example/ex-gwe-barends/mf6gwe",
]
ex-gwe-bhe = [
    "mf6/example/ex-gwe-bhe/mf6gwf",
    "mf6/example/ex-gwe-bhe/mf6gwe",
]
ex-gwe-danckwerts = [
    "mf6/example/ex-gwe-danckwerts",
]
ex-gwe-geotherm = [
    "mf6/example/ex-gwe-geotherm/mf6gwf",
    "mf6/example/ex-gwe-geotherm/mf6gwe",
]
ex-gwe-prt = [
    "mf6/example/ex-gwe-prt/gwf",
    "mf6/example/ex-gwe-prt/gwe",
    "mf6/example/ex-gwe-prt/prt",
]
ex-gwe-radial-slow = [
    "mf6/example/ex-gwe-radial-slow/mf6gwf",
    "mf6/example/ex-gwe-radial-slow/mf6gwe-b",
]
ex-gwe-vsc = [
    "mf6/example/ex-gwe-vsc",
]
ex-gwf-advtidal = [
    "mf6/example/ex-gwf-advtidal",
]
ex-gwf-bcf2ss-p01a = [
    "mf6/example/ex-gwf-bcf2ss-p01a",
]
ex-gwf-bcf2ss-p02a = [
    "mf6/example/ex-gwf-bcf2ss-p02a",
]
ex-gwf-bump-p01a = [
    "mf6/example/ex-gwf-bump-p01a",
]
ex-gwf-bump-p01b = [
    "mf6/example/ex-gwf-bump-p01b",
]
ex-gwf-bump-p01c = [
    "mf6/example/ex-gwf-bump-p01c",
]
ex-gwf-capture = [
    "mf6/example/ex-gwf-capture",
]
ex-gwf-csub-p01 = [
    "mf6/example/ex-gwf-csub-p01",
]
ex-gwf-csub-p02a = [
    "mf6/example/ex-gwf-csub-p02a",
]
ex-gwf-csub-p02b = [
    "mf6/example/ex-gwf-csub-p02b",
]
ex-gwf-csub-p02c = [
    "mf6/example/ex-gwf-csub-p02c/hb-005",
    "mf6/example/ex-gwf-csub-p02c/es-020",
    "mf6/example/ex-gwf-csub-p02c/es-001",
    "mf6/example/ex-gwf-csub-p02c/hb-002",
    "mf6/example/ex-gwf-csub-p02c/es-010",
    "mf6/example/ex-gwf-csub-p02c/es-100",
    "mf6/example/ex-gwf-csub-p02c/es-002",
    "mf6/example/ex-gwf-csub-p02c/hb-100",
    "mf6/example/ex-gwf-csub-p02c/hb-050",
    "mf6/example/ex-gwf-csub-p02c/hb-010",
    "mf6/example/ex-gwf-csub-p02c/hb-001",
    "mf6/example/ex-gwf-csub-p02c/hb-020",
    "mf6/example/ex-gwf-csub-p02c/es-050",
    "mf6/example/ex-gwf-csub-p02c/es-005",
]
ex-gwf-csub-p03a = [
    "mf6/example/ex-gwf-csub-p03a",
]
ex-gwf-csub-p03b = [
    "mf6/example/ex-gwf-csub-p03b",
]
ex-gwf-csub-p04 = [
    "mf6/example/ex-gwf-csub-p04",
]
ex-gwf-curve-90 = [
    "mf6/example/ex-gwf-curve-90",
]
ex-gwf-curvilin = [
    "mf6/example/ex-gwf-curvilin",
]
ex-gwf-disvmesh = [
    "mf6/example/ex-gwf-disvmesh",
]
ex-gwf-drn-p01a = [
    "mf6/example/ex-gwf-drn-p01a",
]
ex-gwf-drn-p01b = [
    "mf6/example/ex-gwf-drn-p01b",
]
ex-gwf-fhb = [
    "mf6/example/ex-gwf-fhb",
]
ex-gwf-hanic = [
    "mf6/example/ex-gwf-hanic",
]
ex-gwf-hanir = [
    "mf6/example/ex-gwf-hanir",
]
ex-gwf-hanix = [
    "mf6/example/ex-gwf-hanix",
]
ex-gwf-lak-p01 = [
    "mf6/example/ex-gwf-lak-p01",
]
ex-gwf-lak-p02 = [
    "mf6/example/ex-gwf-lak-p02",
]
ex-gwf-lgr = [
    "mf6/example/ex-gwf-lgr",
]
ex-gwf-lgrv-gc = [
    "mf6/example/ex-gwf-lgrv-gc",
]
ex-gwf-lgrv-gr = [
    "mf6/example/ex-gwf-lgrv-gr",
]
ex-gwf-lgrv-lgr = [
    "mf6/example/ex-gwf-lgrv-lgr",
]
ex-gwf-maw-p01a = [
    "mf6/example/ex-gwf-maw-p01a",
]
ex-gwf-maw-p01b = [
    "mf6/example/ex-gwf-maw-p01b",
]
ex-gwf-maw-p02 = [
    "mf6/example/ex-gwf-maw-p02",
]
ex-gwf-maw-p03a = [
    "mf6/example/ex-gwf-maw-p03a",
]
ex-gwf-maw-p03b = [
    "mf6/example/ex-gwf-maw-p03b",
]
ex-gwf-maw-p03c = [
    "mf6/example/ex-gwf-maw-p03c",
]
ex-gwf-nwt-p02a = [
    "mf6/example/ex-gwf-nwt-p02a",
]
ex-gwf-nwt-p02b = [
    "mf6/example/ex-gwf-nwt-p02b",
]
ex-gwf-nwt-p03a = [
    "mf6/example/ex-gwf-nwt-p03a",
]
ex-gwf-nwt-p03b = [
    "mf6/example/ex-gwf-nwt-p03b",
]
ex-gwf-rad-disu = [
    "mf6/example/ex-gwf-rad-disu",
]
ex-gwf-sagehen = [
    "mf6/example/ex-gwf-sagehen",
]
ex-gwf-sfr-p01 = [
    "mf6/example/ex-gwf-sfr-p01",
]
ex-gwf-sfr-p01b = [
    "mf6/example/ex-gwf-sfr-p01b",
]
ex-gwf-sfr-pindersauera = [
    "mf6/example/ex-gwf-sfr-pindersauera",
]
ex-gwf-sfr-pindersauerb = [
    "mf6/example/ex-gwf-sfr-pindersauerb",
]
ex-gwf-spbc = [
    "mf6/example/ex-gwf-spbc",
]
ex-gwf-toth = [
    "mf6/example/ex-gwf-toth",
]
ex-gwf-twri01 = [
    "mf6/example/ex-gwf-twri01",
]
ex-gwf-u1disv = [
    "mf6/example/ex-gwf-u1disv",
]
ex-gwf-u1disv-x = [
    "mf6/example/ex-gwf-u1disv-x",
]
ex-gwf-u1gwfgwf-s1 = [
    "mf6/example/ex-gwf-u1gwfgwf-s1",
]
ex-gwf-u1gwfgwf-s2 = [
    "mf6/example/ex-gwf-u1gwfgwf-s2",
]
ex-gwf-u1gwfgwf-s3 = [
    "mf6/example/ex-gwf-u1gwfgwf-s3",
]
ex-gwf-u1gwfgwf-s4 = [
    "mf6/example/ex-gwf-u1gwfgwf-s4",
]
ex-gwf-whirl = [
    "mf6/example/ex-gwf-whirl",
]
ex-gwf-zaidel = [
    "mf6/example/ex-gwf-zaidel",
]
ex-gwt-gwtgwt-p10 = [
    "mf6/example/ex-gwt-gwtgwt-p10",
]
ex-gwt-hecht-mendez-b = [
    "mf6/example/ex-gwt-hecht-mendez-b/mf6gwf",
    "mf6/example/ex-gwt-hecht-mendez-b/mf6gwt",
]
ex-gwt-hecht-mendez-c = [
    "mf6/example/ex-gwt-hecht-mendez-c/mf6gwf",
    "mf6/example/ex-gwt-hecht-mendez-c/mf6gwt",
]
ex-gwt-henry-a = [
    "mf6/example/ex-gwt-henry-a",
]
ex-gwt-henry-b = [
    "mf6/example/ex-gwt-henry-b",
]
ex-gwt-keating = [
    "mf6/example/ex-gwt-keating/mf6gwf",
    "mf6/example/ex-gwt-keating/mf6prt",
    "mf6/example/ex-gwt-keating/mf6gwt",
]
ex-gwt-moc3d-p01a = [
    "mf6/example/ex-gwt-moc3d-p01a/mf6gwf",
    "mf6/example/ex-gwt-moc3d-p01a/mf6gwt",
]
ex-gwt-moc3d-p01b = [
    "mf6/example/ex-gwt-moc3d-p01b/mf6gwf",
    "mf6/example/ex-gwt-moc3d-p01b/mf6gwt",
]
ex-gwt-moc3d-p01c = [
    "mf6/example/ex-gwt-moc3d-p01c/mf6gwf",
    "mf6/example/ex-gwt-moc3d-p01c/mf6gwt",
]
ex-gwt-moc3d-p01d = [
    "mf6/example/ex-gwt-moc3d-p01d/mf6gwf",
    "mf6/example/ex-gwt-moc3d-p01d/mf6gwt",
]
ex-gwt-moc3d-p02 = [
    "mf6/example/ex-gwt-moc3d-p02/mf6gwf",
    "mf6/example/ex-gwt-moc3d-p02/mf6gwt",
]
ex-gwt-moc3d-p02tg = [
    "mf6/example/ex-gwt-moc3d-p02tg/mf6gwf",
    "mf6/example/ex-gwt-moc3d-p02tg/mf6gwt",
]
ex-gwt-mt3dms-p01a = [
    "mf6/example/ex-gwt-mt3dms-p01a",
]
ex-gwt-mt3dms-p01b = [
    "mf6/example/ex-gwt-mt3dms-p01b",
]
ex-gwt-mt3dms-p01c = [
    "mf6/example/ex-gwt-mt3dms-p01c",
]
ex-gwt-mt3dms-p01d = [
    "mf6/example/ex-gwt-mt3dms-p01d",
]
ex-gwt-mt3dms-p02a = [
    "mf6/example/ex-gwt-mt3dms-p02a/mf6gwf",
    "mf6/example/ex-gwt-mt3dms-p02a/mf6gwt",
]
ex-gwt-mt3dms-p02b = [
    "mf6/example/ex-gwt-mt3dms-p02b/mf6gwf",
    "mf6/example/ex-gwt-mt3dms-p02b/mf6gwt",
]
ex-gwt-mt3dms-p02c = [
    "mf6/example/ex-gwt-mt3dms-p02c/mf6gwf",
    "mf6/example/ex-gwt-mt3dms-p02c/mf6gwt",
]
ex-gwt-mt3dms-p02d = [
    "mf6/example/ex-gwt-mt3dms-p02d/mf6gwf",
    "mf6/example/ex-gwt-mt3dms-p02d/mf6gwt",
]
ex-gwt-mt3dms-p02e = [
    "mf6/example/ex-gwt-mt3dms-p02e/mf6gwf",
    "mf6/example/ex-gwt-mt3dms-p02e/mf6gwt",
]
ex-gwt-mt3dms-p02f = [
    "mf6/example/ex-gwt-mt3dms-p02f/mf6gwf",
    "mf6/example/ex-gwt-mt3dms-p02f/mf6gwt",
]
ex-gwt-mt3dms-p03 = [
    "mf6/example/ex-gwt-mt3dms-p03",
]
ex-gwt-mt3dms-p04a = [
    "mf6/example/ex-gwt-mt3dms-p04a",
]
ex-gwt-mt3dms-p04b = [
    "mf6/example/ex-gwt-mt3dms-p04b",
]
ex-gwt-mt3dms-p04c = [
    "mf6/example/ex-gwt-mt3dms-p04c",
]
ex-gwt-mt3dms-p05 = [
    "mf6/example/ex-gwt-mt3dms-p05",
]
ex-gwt-mt3dms-p06 = [
    "mf6/example/ex-gwt-mt3dms-p06",
]
ex-gwt-mt3dms-p07 = [
    "mf6/example/ex-gwt-mt3dms-p07",
]
ex-gwt-mt3dms-p08 = [
    "mf6/example/ex-gwt-mt3dms-p08",
]
ex-gwt-mt3dms-p09 = [
    "mf6/example/ex-gwt-mt3dms-p09",
]
ex-gwt-mt3dms-p10 = [
    "mf6/example/ex-gwt-mt3dms-p10",
]
ex-gwt-mt3dsupp631 = [
    "mf6/example/ex-gwt-mt3dsupp631/mf6gwf",
    "mf6/example/ex-gwt-mt3dsupp631/mf6gwt",
]
ex-gwt-mt3dsupp632a = [
    "mf6/example/ex-gwt-mt3dsupp632a/mf6gwf",
    "mf6/example/ex-gwt-mt3dsupp632a/mf6gwt",
]
ex-gwt-mt3dsupp632b = [
    "mf6/example/ex-gwt-mt3dsupp632b/mf6gwf",
    "mf6/example/ex-gwt-mt3dsupp632b/mf6gwt",
]
ex-gwt-mt3dsupp632c = [
    "mf6/example/ex-gwt-mt3dsupp632c/mf6gwf",
    "mf6/example/ex-gwt-mt3dsupp632c/mf6gwt",
]
ex-gwt-mt3dsupp82 = [
    "mf6/example/ex-gwt-mt3dsupp82/mf6gwf",
    "mf6/example/ex-gwt-mt3dsupp82/mf6gwt",
]
ex-gwt-prudic2004t2 = [
    "mf6/example/ex-gwt-prudic2004t2/mf6gwf",
    "mf6/example/ex-gwt-prudic2004t2/mf6gwt",
]
ex-gwt-rotate = [
    "mf6/example/ex-gwt-rotate",
]
ex-gwt-saltlake = [
    "mf6/example/ex-gwt-saltlake",
]
ex-gwt-stallman = [
    "mf6/example/ex-gwt-stallman",
]
ex-gwt-synthetic-valley = [
    "mf6/example/ex-gwt-synthetic-valley/mf6gwf",
    "mf6/example/ex-gwt-synthetic-valley/mf6gwt",
]
ex-gwt-uzt-2d-a = [
    "mf6/example/ex-gwt-uzt-2d-a",
]
ex-gwt-uzt-2d-b = [
    "mf6/example/ex-gwt-uzt-2d-b",
]
ex-prt-mp7-p01 = [
    "mf6/example/ex-prt-mp7-p01/gwf",
    "mf6/example/ex-prt-mp7-p01/prt",
]
ex-prt-mp7-p02 = [
    "mf6/example/ex-prt-mp7-p02/gwf",
    "mf6/example/ex-prt-mp7-p02/prt",
]
ex-prt-mp7-p03 = [
    "mf6/example/ex-prt-mp7-p03/gwf",
    "mf6/example/ex-prt-mp7-p03/prt",
]
ex-prt-mp7-p04 = [
    "mf6/example/ex-prt-mp7-p04/gwf",
    "mf6/example/ex-prt-mp7-p04/prt",
]
